# autogenerated
.POSIX:
.SUFFIXES:

ARFLAGS=-cru
CFLAGS=-g -O3 -mtune=native -Wall -Wconversion -pedantic -std=c99
CPPFLAGS=-DNDEBUG -D_XOPEN_SOURCE=500
PREFIX=/usr/local

all: dist/lib/libfrt.a

clean:
	rm -fr dist

doc:
	. tools/conf && doc_init dist/share/doc/frt
	doxygen

doc-upload: doc
	. tools/conf && doc_upload dist/share/doc/frt

install: all
	mkdir -p $(DESTDIR)$(PREFIX)/include/frt $(DESTDIR)$(PREFIX)/lib
	install -m644 dist/include/frt/config.h dist/include/frt/math.h dist/include/frt/os.h dist/include/frt/os_posix.inl $(DESTDIR)$(PREFIX)/include/frt
	install -m644 dist/lib/libfrt.a $(DESTDIR)$(PREFIX)/lib

uninstall:
	rm -f $(DESTDIR)$(PREFIX)/include/frt/config.h $(DESTDIR)$(PREFIX)/include/frt/math.h $(DESTDIR)$(PREFIX)/include/frt/os.h $(DESTDIR)$(PREFIX)/include/frt/os_posix.inl $(DESTDIR)$(PREFIX)/lib/libfrt.a

dist/include/frt/config.h: include/frt/config.h tools/conf
	mkdir -p dist/include/frt
	head >dist/include/frt/config.h.tmp -n 2 include/frt/config.h
	. tools/conf && cc() { $(CC) $(CPPFLAGS) $(CFLAGS) "$$@"; } && detect_limits >>dist/include/frt/config.h.tmp signed off_t RF_OFF sys/types.h
	tail >>dist/include/frt/config.h.tmp -n +3 include/frt/config.h
	mv -f dist/include/frt/config.h.tmp dist/include/frt/config.h

dist/include/frt/math.h: include/frt/math.h
	mkdir -p dist/include/frt
	cp -f include/frt/math.h dist/include/frt/math.h

dist/include/frt/os.h: include/frt/os.h
	mkdir -p dist/include/frt
	cp -f include/frt/os.h dist/include/frt/os.h

dist/include/frt/os_posix.inl: include/frt/os_posix.inl
	mkdir -p dist/include/frt
	cp -f include/frt/os_posix.inl dist/include/frt/os_posix.inl

dist/lib/libfrt.a: dist/tmp/src/os_posix.c.o
	mkdir -p dist/lib
	$(AR) $(ARFLAGS) dist/lib/libfrt.a dist/tmp/src/os_posix.c.o

dist/tmp/src/os_posix.c.o: dist/include/frt/config.h dist/include/frt/math.h dist/include/frt/os.h dist/include/frt/os_posix.inl src/os_posix.c
	mkdir -p dist/tmp/src
	$(CC) $(CPPFLAGS) -Idist/include $(CFLAGS) -o dist/tmp/src/os_posix.c.o -c src/os_posix.c

.PHONY: all clean doc doc-upload install uninstall
